# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "puphpet/ubuntu1404-x64"

  config.vm.synced_folder "../", "/cmus_bundler", :nfs => true  

  config.vm.network "private_network", ip: "192.168.100.200"

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y python-pip git

     # install cmus
     sudo apt-get install -y cmus

     # install node + npm
     sudo apt-get install -y nodejs npm

     # fix nodejs->node linux issue
     sudo ln -s /usr/bin/nodejs /usr/bin/node

     # install cmus-bundler
     # sudo npm install -g cmus-bundler

     # make audio work
     sudo usermod -a -G audio vagrant

     # create logs directory
     mkdir /home/vagrant/logs

     # create cmus directory
     mkdir /home/vagrant/.cmus

     # create music directory
     mkdir /home/vagrant/music

     # download test mp3 file
     curl -o /home/vagrant/music/test.mp3 http://lcweb4.loc.gov/afc/afcreed/130/13033b03.mp3

     # create cmus rc file
     echo "source /cmus_bundler/test/sample_rc" > /home/vagrant/.cmus/rc

   SHELL
end

#
